import os
from pathlib import Path

from azure.ai.projects.aio import AIProjectClient
from azure.ai.projects.models import ThreadMessage

from terminal_colors import TerminalColors as tc


class Utilities:
    def log_msg_green(self, msg: str) -> None:
        """Print a message in green."""
        print(f"{tc.GREEN}{msg}{tc.RESET}")

    def log_msg_purple(self, msg: str) -> None:
        """Print a message in purple."""
        print(f"{tc.PURPLE}{msg}{tc.RESET}")

    def log_token_blue(self, msg: str) -> None:
        """Print a token in blue."""
        print(f"{tc.BLUE}{msg}{tc.RESET}", end="", flush=True)
        
    async def get_file(self, project_client: AIProjectClient, file_id: str, attachment_name: str) -> str | None:
        """Retrieve the file, save it locally, and return its path."""
        self.log_msg_green(f"Getting file with ID: {file_id}")

        file_name, file_extension = os.path.splitext(
            os.path.basename(attachment_name.split(":")[-1])
        )
        file_name = f"{file_name}.{file_id}{file_extension}"

        env = os.getenv("ENVIRONMENT", "local")
        folder_path = Path(f"{'src/workshop/' if env == 'container' else ''}files/file")
        folder_path.mkdir(parents=True, exist_ok=True)

        file_path = folder_path / file_name

        try:
            file_content_stream = await project_client.agents.get_file_content(file_id)
            
            with file_path.open("wb") as file:
                async for chunk in file_content_stream:
                    if isinstance(chunk, bytes):
                        file.write(chunk)
                    else:
                        print(f"❌ Unexpected data type in file stream: {type(chunk)}")
            
            self.log_msg_green(f"✅ File saved to {file_path}")

            # Cleanup the remote file
            await project_client.agents.delete_file(file_id)

            return str(file_path)  # Return the saved file path

        except Exception as e:
            print(f"❌ Error saving file {file_name}: {e}")
            return None  # Return None in case of failure

    async def get_files(self, message: ThreadMessage, project_client: AIProjectClient) -> None:
        """Get the files from the message and download them."""
        print("Getting files defined by utilities")
        
        # Step 1: Check for the attachments containing file IDs
        if message.attachments:
            for attachment in message.attachments:
                file_id = attachment.get('file_id')  # Get the file ID from the attachment
                
                if file_id:
                    # Extract file name or use "unknown" if not available
                    attachment_name = (
                        "unknown" if not message.file_path_annotations else message.file_path_annotations[0].text
                    )
                    
                    # Step 2: Download the file using the file ID
                    await self.get_file(project_client, file_id, attachment_name)
                    
        print("File retrieval completed")

    async def create_vector_store(self, project_client: AIProjectClient, files: list[str], vector_name_name: str) -> None:
        """Upload a file to the project from message and then use the vector database to answer related questions."""

        file_ids = []
        env = os.getenv("ENVIRONMENT", "local")
        prefix = "src/workshop/" if env == "container" else ""

        # Upload the files
        for file in files:
            file_path = Path(f"{prefix}{file}")
            self.log_msg_purple(f"Uploading file: {file_path}")
            
            file_info = await project_client.agents.upload_file(file_path=file_path, purpose="assistants")
            file_ids.append(file_info.id)

        self.log_msg_purple("Creating the vector store")

        # Create a vector store
        vector_store = await project_client.agents.create_vector_store_and_poll(
            file_ids=file_ids, name=vector_name_name
        )

        self.log_msg_purple(
            f"Vector store created and files added.")
        return vector_store
    
    async def handle_generated_image(self, message: ThreadMessage, project_client: AIProjectClient) -> list[str]:
        """Handle and save images or charts generated by the code interpreter."""
        print("Checking for generated images or charts...")

        saved_files = []

        if message.attachments:
            for attachment in message.attachments:
                file_id = attachment.get('file_id')
                attachment_name = attachment.get('file_name', 'generated_image.png')

                # Check if the attachment is an image
                mime_type, _ = mimetypes.guess_type(attachment_name)
                if mime_type and mime_type.startswith("image"):
                    print(f"🖼️ Detected an image: {attachment_name} (ID: {file_id})")

                    # Save the image and store the file path
                    file_path = await self.get_file(project_client, file_id, attachment_name)
                    if file_path:
                        saved_files.append(file_path)  # Store the saved file path

        return saved_files  # Return the list of saved files
